[build]
  command = ""
  publish = "dist" # o b칩rralo si no tienes front

# (Opcional) d칩nde est치n tus funciones fuente
[functions]
  directory = "netlify/functions"

# Programa la funci칩n por nombre (sin [[ ]])
[functions."actualizar-stock"]
  schedule = "@daily"  # @hourly, @weekly, o cron "0 6 * * *"
